name: Tailscale SSH Debugging

on:
  workflow_dispatch:

jobs:
  debug_job:
    runs-on: ubuntu-latest
    
    steps:

      - name: Şifre Belirle
        run: echo "runner:12345" | sudo chpasswd

    
      - name: Repoyu Klonla
        uses: actions/checkout@v4

      - name: Tailscale'e Bağlan
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTH_KEY }}

      - name: SSH Bilgilerini Göster ve Bekle
        run: |
          # Runner'ın Tailscale IP'sini al
          TS_IP=$(tailscale ip -4)
          echo "-------------------------------------------------------"
          echo "Tailscale IP Adresin: $TS_IP"
          echo "Bağlanmak için terminaline şunu yaz:"
          echo "ssh runner@$TS_IP"
          echo "-------------------------------------------------------"
          
          # Makineyi açık tutmak için (örneğin 1 saat) bekletiyoruz
          # Eğer işin biterse GitHub Actions panelinden 'Cancel run' diyebilirsin.
           
